---

- hosts: all

  tasks:
  ####################################################################
  ####################################################################

  - name: ensure dependencies (Debian)
    apt: pkg={{item}} state=installed
    with_items:
    - git
    - automake
    - libtool
    - build-essential
    - bison
    - flex
    - libreadline-dev
    when: ansible_os_family == "Debian"
    become: yes
  
  - name: increase semaphores
    sysctl: name=kernel.sem value="1000 128000 128 512"
    become: yes
  
  - name: increase open files
    lineinfile:
      dest: /etc/security/limits.d/cluster.conf
      line: "{{ansible_ssh_user}}  soft  nofile  65535"
      state: present
      create: yes
    become: yes
  
  - name: clone postgres sources
    git: repo={{pg_repo}}
      dest={{pg_src}}
      version={{pg_version_tag}}
      depth=1
      accept_hostkey=True
      key_file={{pg_repo_key}}
    register: pg_sources
  
  - name: build and install
    shell: env CFLAGS="-O0" ./configure --prefix={{pg_dst}} --enable-debug --without-zlib && make clean && make -j {{makejobs}} && make install
    args:
      chdir: "{{pg_src}}"

  # - debug: var=pg_src

  - name: build multimaster
    shell: "make clean && make -j {{makejobs}} install"
    args:
      chdir: "{{pg_src}}/contrib/mmts"
    environment:
      LD_LIBRARY_PATH: "{{pg_dst}}/lib/"
 
  - name: set up hostnames 
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
      state: present
    when: "{{hostvars[item].ansible_default_ipv4.address is defined}}"
    with_items: "{{groups['all']}}"
    become: yes

